version: '2'

services:
    db:
        image: postgres
        environment:
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
          - POSTGRES_DB=test
        ports:
          - "5432:5432"
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        networks:
        - symfony-network
    nginx-back:
        image: nginx:latest
        ports:
            - "8080:81"
        volumes:
            - ./symfony:/symfony
            - ./config-nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony-network
    php:
      build: php-fpm
      working_dir: /symfony
      volumes:
        - ./uca-aranceles-back:/symfony
        #- ./symfony:/symfony
        - ./config-php:/usr/local/etc/php
      networks:
        - symfony-network
    front:
        build: ./angular
        volumes:
          - "/app/node_modules"
          - "./angular:/app"   
        networks:
          - symfony-network
    nginx-front:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./config-nginx/site2.conf:/etc/nginx/conf.d/default.conf
      networks:
          - symfony-network
networks:
    symfony-network:
        driver: bridge

    # php:
    #     image: php:fpm
    #     volumes:
    #         - ./symfony:/symfony
    #       - ./config-php:/usr/local/etc/php
    #     networks:
    #         - symfony-network